# Generated by Django 4.2.5 on 2023-09-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre del Departamento')),
                ('shor_name', models.CharField(max_length=20, verbose_name='Nombre Corto')),
                ('status', models.BooleanField(default=False, verbose_name='Inactivo')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Registro Departamentos',
                'unique_together': {('name', 'shor_name')},
            },
        ),
    ]
