# Generated by Django 4.2.5 on 2023-09-21 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departament', '0002_shifts_alter_departament_shor_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shifts',
        ),
    ]
