# Generated by Django 4.2.5 on 2023-09-26 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departament', '0003_delete_shifts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departament',
            options={'verbose_name': 'Departamento', 'verbose_name_plural': 'Departamentos'},
        ),
    ]
