# Generated by Django 4.2.5 on 2023-10-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departament', '0004_alter_departament_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='departament',
            name='description',
            field=models.CharField(max_length=80, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='departament',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
