# Generated by Django 4.2.5 on 2023-10-03 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departament', '0005_departament_description_departament_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departament',
            name='description',
            field=models.CharField(max_length=100, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='departament',
            name='image',
            field=models.ImageField(null=True, upload_to='departament'),
        ),
    ]
