# Generated by Django 4.2.5 on 2023-10-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departament', '0006_alter_departament_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departament',
            name='description',
            field=models.CharField(max_length=150, null=True, verbose_name='Descripción'),
        ),
    ]
