# Generated by Django 4.2.5 on 2023-09-26 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.DateField(null=True, verbose_name='Fecha de nacimiento'),
        ),
    ]
