# Generated by Django 4.2.5 on 2023-09-26 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_history_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='Fecha del historial'),
        ),
    ]
