# Generated by Django 4.2.5 on 2023-09-26 01:08

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_delete_shifts'),
        ('user', '0004_alter_history_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name': 'Historial', 'verbose_name_plural': 'Historiales medicos'},
        ),
        migrations.AlterField(
            model_name='history',
            name='history',
            field=ckeditor.fields.RichTextField(verbose_name='Historial'),
        ),
        migrations.AlterField(
            model_name='history',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='Paciente'),
        ),
        migrations.CreateModel(
            name='Shifts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=8, verbose_name='DNI del Paciente')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('time', models.CharField(choices=[('0', '8:00'), ('1', '8:30'), ('2', '9:00'), ('3', '10:00'), ('4', '11:00')], max_length=1, verbose_name='Horario')),
                ('medic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
            options={
                'verbose_name': 'Turnos',
                'verbose_name_plural': 'Registro de Turnos',
            },
        ),
    ]
