# Generated by Django 4.2.5 on 2023-10-03 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_delete_shifts'),
        ('user', '0005_alter_history_options_alter_history_history_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shifts',
            name='medic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee', verbose_name='Especialista'),
        ),
    ]
