# Generated by Django 4.2.6 on 2023-10-16 00:36

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=40, verbose_name='Apellido')),
                ('birthdate', models.DateField(null=True, verbose_name='Fecha de nacimiento')),
                ('sex', models.CharField(choices=[('0', 'Masculino'), ('1', 'Femenino'), ('3', 'Otro')], max_length=1, verbose_name='Sexo')),
                ('email', models.EmailField(blank=True, max_length=45, null=True, verbose_name='Email')),
                ('dni', models.CharField(max_length=8, unique=True, verbose_name='DNI')),
                ('type', models.CharField(choices=[('0', 'Titular'), ('1', 'Co-Titular'), ('3', 'Familiar')], max_length=1, verbose_name='Tipo de afiliado')),
                ('status', models.BooleanField(default=False, verbose_name='Inactivo')),
            ],
            options={
                'verbose_name': 'Afiliado',
                'verbose_name_plural': 'Registro de afiliado',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', ckeditor.fields.RichTextField(verbose_name='Historial')),
                ('date', models.DateField(auto_now=True, verbose_name='Fecha del historial')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.user', verbose_name='Afiliado')),
            ],
            options={
                'verbose_name': 'Historial',
                'verbose_name_plural': 'Historiales medicos',
            },
        ),
    ]
