# Generated by Django 4.2.6 on 2023-10-16 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_alter_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dni2',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True, verbose_name='DNI del titular'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('0', 'Titular'), ('1', 'Co-Titular'), ('3', 'Familiar')], default='1', max_length=1, verbose_name='Tipo de afiliado'),
        ),
    ]
