# Generated by Django 4.2.6 on 2023-10-25 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_domicilio_medicacion_paciente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCertificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de certificado',
                'verbose_name_plural': 'Tipos de certificado',
            },
        ),
        migrations.AlterModelOptions(
            name='domicilio',
            options={'verbose_name': 'Domicilio', 'verbose_name_plural': 'Registro de Domicilios'},
        ),
        migrations.AlterModelOptions(
            name='medicacion',
            options={'verbose_name': 'Medicamentos', 'verbose_name_plural': 'Registro de medicamentos'},
        ),
        migrations.AlterModelOptions(
            name='paciente',
            options={'verbose_name': 'Paciente', 'verbose_name_plural': 'Registro de pacientes'},
        ),
        migrations.AlterModelOptions(
            name='pacientetratamientomedico',
            options={'verbose_name': 'Tratamiento', 'verbose_name_plural': 'Tratamientos por paciente'},
        ),
        migrations.AlterModelOptions(
            name='parroquia',
            options={'verbose_name': 'Parroquia', 'verbose_name_plural': 'Registro de Parroquias'},
        ),
        migrations.AlterModelOptions(
            name='referente',
            options={'verbose_name': 'Referente Parroquial', 'verbose_name_plural': 'Registro de Referentes'},
        ),
        migrations.AlterModelOptions(
            name='telefono',
            options={'verbose_name': 'Telefono', 'verbose_name_plural': 'Registro de Telefonos'},
        ),
        migrations.AlterModelOptions(
            name='tratamientomedico',
            options={'verbose_name': 'Tratamiento Medico', 'verbose_name_plural': 'Tipos de tratamiento'},
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificado', models.FileField(upload_to='certificados/')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.paciente')),
                ('tipocertificado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.tipocertificado')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Registro de pacientes',
            },
        ),
    ]
