# Generated by Django 4.2.6 on 2023-10-25 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_tipocertificado_alter_domicilio_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='certificado_de_convivencia',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='certificado_de_matrimonio',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='certificado_de_tutela',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='id',
        ),
        migrations.AlterField(
            model_name='paciente',
            name='credencial',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
