# Generated by Django 4.2.6 on 2023-10-25 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_remove_paciente_certificado_de_convivencia_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificado',
            options={'verbose_name': 'Certificado', 'verbose_name_plural': 'Registro de certificados'},
        ),
        migrations.RemoveField(
            model_name='tipocertificado',
            name='titulo',
        ),
        migrations.AddField(
            model_name='paciente',
            name='dnititular',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='DNI del Titular'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='sex',
            field=models.CharField(choices=[('0', 'Masculino'), ('1', 'Femenino'), ('3', 'Otro')], default='0', max_length=1, verbose_name='Sexo'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='tipo',
            field=models.CharField(choices=[('0', 'Titular'), ('1', 'Familiar')], default='0', max_length=1, verbose_name='Tipo de afiliación'),
        ),
        migrations.AddField(
            model_name='tipocertificado',
            name='Tipo',
            field=models.CharField(default=1, max_length=100, verbose_name='Tipo de certificado'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paciente',
            name='dni',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
