# Generated by Django 4.2.6 on 2023-11-26 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0010_alter_tipotelefono_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domicilio',
            name='piso',
        ),
        migrations.AddField(
            model_name='referente',
            name='alias',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='referente',
            name='apellidos',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='referente',
            name='nombres',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
