# Generated by Django 4.2.6 on 2023-11-26 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0011_remove_domicilio_piso_referente_alias_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paciente',
            options={'verbose_name': 'Socio', 'verbose_name_plural': 'Registro de socios'},
        ),
        migrations.RemoveField(
            model_name='domicilio',
            name='entre_calles',
        ),
        migrations.AddField(
            model_name='domicilio',
            name='partido',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='referente',
            name='parroquia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.parroquia'),
        ),
    ]
