# Generated by Django 4.2.6 on 2023-11-26 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0012_alter_paciente_options_remove_domicilio_entre_calles_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parroquia',
            name='domicilio',
        ),
        migrations.AlterField(
            model_name='referente',
            name='parroquia',
            field=models.ForeignKey(default='S/N', on_delete=django.db.models.deletion.CASCADE, to='patient.parroquia'),
        ),
    ]
