# Generated by Django 4.2.6 on 2023-11-30 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0014_remove_paciente_telefonos_remove_telefono_paciente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='tipo',
        ),
        migrations.AddField(
            model_name='paciente',
            name='categoria',
            field=models.CharField(choices=[('0', 'Demanda Espontanea'), ('1', 'Socio'), ('3', 'Socio Afiliado')], default='0', max_length=1, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='condicion_de_solicitud',
            field=models.CharField(choices=[('0', 'Titular'), ('1', 'Familiar')], default='0', max_length=1, verbose_name='Condición de solicitud'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='dni',
            field=models.CharField(help_text="<span style='color: red;font-weight: bold; text-transform: uppercase;'>¡Ingresar sin caracteres especiales o espacios ( - , * , _, . )!</span>", max_length=8, unique=True, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.telefono', verbose_name='Número de contacto'),
        ),
        migrations.AlterField(
            model_name='telefono',
            name='numero_de_telefono',
            field=models.CharField(max_length=20, verbose_name='Número de contacto'),
        ),
        migrations.AlterField(
            model_name='telefono',
            name='numero_de_telefono2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de contacto 2'),
        ),
    ]
