# Generated by Django 4.2.6 on 2023-11-30 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0015_remove_paciente_tipo_paciente_categoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='estado_de_monotributo',
        ),
        migrations.AddField(
            model_name='paciente',
            name='monotributo',
            field=models.CharField(choices=[('0', 'Categoria A'), ('1', 'Categoria B'), ('2', 'Categoria C'), ('3', 'Categoria D'), ('4', 'Otro'), ('5', 'No tiene')], default='0', max_length=1, verbose_name='Monotributo'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='condicion_de_solicitud',
            field=models.CharField(choices=[('0', 'Titular'), ('1', 'Familiar'), ('2', 'No Aplica')], default='0', max_length=1, verbose_name='Condición de solicitud'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='patient.telefono', verbose_name='Número de contacto'),
        ),
    ]
