# Generated by Django 4.2.6 on 2023-12-02 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0018_alter_referente_alias_alter_referente_parroquia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referente',
            name='parroquia',
            field=models.ForeignKey(blank=True, default='S/N', null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.parroquia'),
        ),
    ]
