# Generated by Django 4.2.5 on 2023-09-21 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=40, verbose_name='Apellido')),
                ('birthdate', models.DateField(null=True, verbose_name='Fecha de nacimiento')),
                ('phone', models.CharField(blank=True, max_length=10, null=True, verbose_name='Telefono')),
                ('sex', models.CharField(choices=[('0', 'Masculino'), ('1', 'Femenino'), ('3', 'Otro')], max_length=1, verbose_name='Sexo')),
                ('email', models.EmailField(blank=True, max_length=45, null=True, verbose_name='Email')),
                ('dni', models.CharField(max_length=8, unique=True, verbose_name='DNI')),
                ('job', models.CharField(choices=[('0', 'Contador'), ('1', 'Administrativo'), ('2', 'Desarrollador'), ('3', 'Analista Funcional'), ('4', 'Otros')], max_length=1, verbose_name='Puesto')),
                ('status', models.BooleanField(default=False, verbose_name='Inactivo')),
            ],
            options={
                'verbose_name': 'Empleados',
                'verbose_name_plural': 'Registro de empleados',
            },
        ),
    ]
