# Generated by Django 4.2.6 on 2023-10-16 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departament', '0007_alter_departament_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=40, verbose_name='Apellido')),
                ('birthdate', models.DateField(null=True, verbose_name='Fecha de nacimiento')),
                ('sex', models.CharField(choices=[('0', 'Masculino'), ('1', 'Femenino'), ('3', 'Otro')], max_length=1, verbose_name='Sexo')),
                ('email', models.EmailField(blank=True, max_length=45, null=True, verbose_name='Email')),
                ('dni', models.CharField(max_length=8, unique=True, verbose_name='DNI')),
                ('rol', models.CharField(choices=[('0', 'Administrativo'), ('1', 'Medico'), ('3', 'Otro')], default='3', max_length=1, verbose_name='Rol del empleado')),
                ('status', models.BooleanField(default=False, verbose_name='Inactivo')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departament.departament', verbose_name='Área')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Registro de empleado',
            },
        ),
    ]
