# Generated by Django 4.2.5 on 2023-09-21 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_departament'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shifts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=8, verbose_name='DNI del Paciente')),
                ('date', models.CharField(max_length=20, verbose_name='Nombre Corto')),
                ('time', models.CharField(choices=[('0', '8:00'), ('1', '8:30'), ('2', '9:00'), ('3', '10:00'), ('4', '11:00')], max_length=1, verbose_name='Horario')),
                ('employee', models.ManyToManyField(to='employee.employee')),
            ],
            options={
                'verbose_name': 'Turnos',
                'verbose_name_plural': 'Registro de Turnos',
            },
        ),
    ]
