# Generated by Django 4.2.5 on 2023-09-22 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_shifts_date_alter_shifts_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='job',
            field=models.CharField(choices=[('0', 'Pediatra'), ('1', 'Cirujia'), ('2', 'Clinica'), ('3', 'Urologia'), ('4', 'Otros')], max_length=1, verbose_name='Puesto'),
        ),
    ]
