# Generated by Django 4.2.5 on 2023-09-26 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_alter_employee_job'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shifts',
        ),
    ]
